//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace InformationSystems.API
{

    public partial class Company : XPObject
    {
        long fInternalId;
        public long InternalId
        {
            get { return fInternalId; }
            set { SetPropertyValue<long>(nameof(InternalId), ref fInternalId, value); }
        }
        string fRegisteredName;
        public string RegisteredName
        {
            get { return fRegisteredName; }
            set { SetPropertyValue<string>(nameof(RegisteredName), ref fRegisteredName, value); }
        }
        string fVat;
        public string Vat
        {
            get { return fVat; }
            set { SetPropertyValue<string>(nameof(Vat), ref fVat, value); }
        }
        string fAddress;
        public string Address
        {
            get { return fAddress; }
            set { SetPropertyValue<string>(nameof(Address), ref fAddress, value); }
        }
        byte[] fLogo;
        [MemberDesignTimeVisibility(true)]
        public byte[] Logo
        {
            get { return fLogo; }
            set { SetPropertyValue<byte[]>(nameof(Logo), ref fLogo, value); }
        }
        bool fIsProvider;
        public bool IsProvider
        {
            get { return fIsProvider; }
            set { SetPropertyValue<bool>(nameof(IsProvider), ref fIsProvider, value); }
        }
        string fConflictCallbackUrl;
        public string ConflictCallbackUrl
        {
            get { return fConflictCallbackUrl; }
            set { SetPropertyValue<string>(nameof(ConflictCallbackUrl), ref fConflictCallbackUrl, value); }
        }
        bool fConflictNotification;
        public bool ConflictNotification
        {
            get { return fConflictNotification; }
            set { SetPropertyValue<bool>(nameof(ConflictNotification), ref fConflictNotification, value); }
        }
        string fPasswordHash;
        public string PasswordHash
        {
            get { return fPasswordHash; }
            set { SetPropertyValue<string>(nameof(PasswordHash), ref fPasswordHash, value); }
        }
        string fPasswordSalt;
        public string PasswordSalt
        {
            get { return fPasswordSalt; }
            set { SetPropertyValue<string>(nameof(PasswordSalt), ref fPasswordSalt, value); }
        }
        DateTime fDateCreated;
        public DateTime DateCreated
        {
            get { return fDateCreated; }
            set { SetPropertyValue<DateTime>(nameof(DateCreated), ref fDateCreated, value); }
        }
        bool fIsActive;
        public bool IsActive
        {
            get { return fIsActive; }
            set { SetPropertyValue<bool>(nameof(IsActive), ref fIsActive, value); }
        }
        string fRemarks;
        public string Remarks
        {
            get { return fRemarks; }
            set { SetPropertyValue<string>(nameof(Remarks), ref fRemarks, value); }
        }
        [Association(@"InfrastructureModificationRequestReferencesCompany")]
        public XPCollection<InfrastructureModificationRequest> InfrastructureModificationRequests { get { return GetCollection<InfrastructureModificationRequest>(nameof(InfrastructureModificationRequests)); } }
    }

}
