//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace InformationSystems.API
{

    public partial class GeoLocation : XPObject
    {
        double? fAltitude;
        public double? Altitude
        {
            get { return fAltitude; }
            set { SetPropertyValue<double?>(nameof(Altitude), ref fAltitude, value); }
        }
        double fLatitude;
        public double Latitude
        {
            get { return fLatitude; }
            set { SetPropertyValue<double>(nameof(Latitude), ref fLatitude, value); }
        }
        double fLongitude;
        public double Longitude
        {
            get { return fLongitude; }
            set { SetPropertyValue<double>(nameof(Longitude), ref fLongitude, value); }
        }
        Infrastructure fInfrastructure;
        [Association(@"GeoLocationReferencesInfrastructure")]
        public Infrastructure Infrastructure
        {
            get { return fInfrastructure; }
            set { SetPropertyValue<Infrastructure>(nameof(Infrastructure), ref fInfrastructure, value); }
        }
    }

}
