//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace InformationSystems.API
{

    public partial class InfrastructureModificationRequest : XPObject
    {
        int fInternalId;
        public int InternalId
        {
            get { return fInternalId; }
            set { SetPropertyValue<int>(nameof(InternalId), ref fInternalId, value); }
        }
        string fCallbackUrl;
        [Size(SizeAttribute.Unlimited)]
        public string CallbackUrl
        {
            get { return fCallbackUrl; }
            set { SetPropertyValue<string>(nameof(CallbackUrl), ref fCallbackUrl, value); }
        }
        Company fCompany;
        [Association(@"InfrastructureModificationRequestReferencesCompany")]
        public Company Company
        {
            get { return fCompany; }
            set { SetPropertyValue<Company>(nameof(Company), ref fCompany, value); }
        }
        DateTime fDateCreated;
        public DateTime DateCreated
        {
            get { return fDateCreated; }
            set { SetPropertyValue<DateTime>(nameof(DateCreated), ref fDateCreated, value); }
        }
        DateTime fDateResponded;
        public DateTime DateResponded
        {
            get { return fDateResponded; }
            set { SetPropertyValue<DateTime>(nameof(DateResponded), ref fDateResponded, value); }
        }
        bool fSuccess;
        public bool Success
        {
            get { return fSuccess; }
            set { SetPropertyValue<bool>(nameof(Success), ref fSuccess, value); }
        }
        string fInitialResponse;
        [Size(SizeAttribute.Unlimited)]
        public string InitialResponse
        {
            get { return fInitialResponse; }
            set { SetPropertyValue<string>(nameof(InitialResponse), ref fInitialResponse, value); }
        }
        string fOriginalGeoJson;
        [Size(SizeAttribute.Unlimited)]
        public string OriginalGeoJson
        {
            get { return fOriginalGeoJson; }
            set { SetPropertyValue<string>(nameof(OriginalGeoJson), ref fOriginalGeoJson, value); }
        }
    }

}
