//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace InformationSystems.API
{

    public partial class JobsLog : XPObject
    {
        string fDateCreated;
        public string DateCreated
        {
            get { return fDateCreated; }
            set { SetPropertyValue<string>(nameof(DateCreated), ref fDateCreated, value); }
        }
        string fDateCompleted;
        public string DateCompleted
        {
            get { return fDateCompleted; }
            set { SetPropertyValue<string>(nameof(DateCompleted), ref fDateCompleted, value); }
        }
        string fEntityId;
        public string EntityId
        {
            get { return fEntityId; }
            set { SetPropertyValue<string>(nameof(EntityId), ref fEntityId, value); }
        }
        string fEntityType;
        public string EntityType
        {
            get { return fEntityType; }
            set { SetPropertyValue<string>(nameof(EntityType), ref fEntityType, value); }
        }
        string fErrorMessage;
        public string ErrorMessage
        {
            get { return fErrorMessage; }
            set { SetPropertyValue<string>(nameof(ErrorMessage), ref fErrorMessage, value); }
        }
    }

}
